### ISSUE TITLE
Installation for virtual env for conda .yaml file

### ISSUE THREAD

**Issue by YifangZhang** [c3aidti/genomicsExample#1]
I found it is easier to use .yaml file but it failed:

## if I am using condo -p command:

> (base) ITs-MacBook-Pro-2:python zhang303$ conda create -f ./env.yaml -p ./venv
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - ./env.yaml
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/osx-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.

## if I am using the condo -n command:

> (base) ITs-MacBook-Pro-2:python zhang303$ conda env create -f env.yaml -n geno
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> ... <all packages>...

**Comment by krafczyk** [comment]
Try

`conda env create -f ./env.yaml -p ./venv`

**Comment by YifangZhang** [comment]
`(base) ITs-MacBook-Pro-2:python zhang303$ conda env create -f ./env.yaml -p ./venv
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libdeflate==1.6=h516909a_0
  - xorg-libxdmcp==1.1.3=h516909a_0
  - _openmp_mutex==4.5=0_gnu
  - libclang==9.0.1=default_hde54327_0
  - libcurl==7.69.1=hf7181ac_0
  - phyml==3.3.20190909=h516909a_0
  - libllvm9==9.0.1=he513fc3_1
  - nss==3.47=he751ad9_0
  - readline==8.0=hf8c457e_0
  - libedit==3.1.20191231=h46ee950_0
  - libxcb==1.13=h14c3975_1002
  - pyzmq==19.0.1=py36h9947dbf_0
  - clustalw==2.1=hc9558a2_5
  - libffi==3.2.1=he1b5a44_1007
  - krb5==1.17.1=h2fd8d38_0
  - xorg-libsm==1.2.3=h84519dc_1000
  - libgcc-ng==9.2.0=h24d8f2e_2
  - gettext==0.19.8.1=hc5be6a0_1002
  - icu==64.2=he1b5a44_1
  - liblapack==3.8.0=8_h6e990d7_netlib
  - mistune==0.8.4=py36h8c4c3a4_1001
  - lxml==4.5.1=py36h17c4326_0
  - xorg-libxext==1.3.4=h516909a_0
  - libgcc==7.2.0=h69d50b8_2
  - reportlab==3.5.42=py36hcce1d1f_0
  - jpeg==9d=h516909a_0
  - libxml2==2.9.10=hee79883_0
  - _libgcc_mutex==0.1=conda_forge
  - pandas==0.24.2=py36hf484d3e_0
  - python==3.6.10=h8356626_1011_cpython
  - xorg-libxau==1.0.9=h14c3975_0
  - nspr==4.25=he1b5a44_0
  - libstdcxx-ng==9.2.0=hdf63c60_2
  - openmpi==4.0.4=hdf1f1ad_0
  - xz==5.2.5=h516909a_0
  - libcblas==3.8.0=8_h6e990d7_netlib
  - libopenblas==0.3.7=h5ec1e0e_6
  - zlib==1.2.11=h516909a_1006
  - libgomp==9.2.0=h24d8f2e_2
  - qt==5.12.5=hd8c4c69_1
  - tk==8.6.10=hed695b0_0
  - bzip2==1.0.8=h516909a_2
  - intel-openmp==2019.4=243
  - msgpack-python==1.0.0=py36hdb11119_1
  - libtiff==4.1.0=hc7e4089_6
  - libuuid==2.32.1=h14c3975_1000
  - libblas==3.8.0=8_h6e990d7_netlib
  - libiconv==1.15=h516909a_1006
  - pyqt==5.12.3=py36haa643ae_3
  - samtools==1.9=h10a08f8_12
  - fontconfig==2.13.1=h86ecdb6_1001
  - xorg-libxrender==0.9.10=h516909a_1002
  - pcre==8.44=he1b5a44_0
  - openssl==1.1.1g=h516909a_0
  - gst-plugins-base==1.14.5=h0935bb2_2
  - xorg-kbproto==1.0.7=h14c3975_1002
  - freetype==2.10.2=he06d7ca_0
  - brotlipy==0.7.0=py36h8c4c3a4_1000
  - libgfortran-ng==7.5.0=hdf63c60_6
  - gstreamer==1.14.5=h36ae1b5_2
  - libwebp-base==1.1.0=h516909a_3
  - cryptography==2.9.2=py36h45558ae_0
  - expat==2.2.9=he1b5a44_2
  - zstd==1.4.4=h6597ccf_3
  - xorg-renderproto==0.11.1=h14c3975_1002
  - pillow==7.1.2=py36h8328e55_0
  - pthread-stubs==0.4=h14c3975_1001
  - scipy==1.2.1=py36h09a28d5_1
  - ld_impl_linux-64==2.34=h53a641e_5
  - tornado==6.0.4=py36h8c4c3a4_1
  - dbus==1.13.6=he372182_0
  - libssh2==1.9.0=hab1572f_2
  - libpng==1.6.37=hed695b0_1
  - glib==2.64.3=h6f030ca_0
  - zeromq==4.3.2=he1b5a44_2
  - xorg-libice==1.0.10=h516909a_0
  - libxslt==1.1.33=h31b3aaa_0
  - pysam==0.16.0.1=py36h71d3148_0
  - cffi==1.14.0=py36hd463f26_0
  - numpy==1.12.1=py36he24570b_1
  - xorg-xextproto==7.3.0=h14c3975_1002
  - libxkbcommon==0.10.0=he1b5a44_0
  - ncurses==6.1=hf484d3e_1002
  - htslib==1.9=h4da6232_3
  - sqlite==3.30.1=hcee41ef_0
  - xorg-xproto==7.0.31=h14c3975_1007
  - lz4-c==1.9.2=he1b5a44_1
  - xorg-libx11==1.6.9=h516909a_0
  - curl==7.69.1=h33f0ec9_0
  - libsodium==1.0.17=h516909a_0
  - markupsafe==1.1.1=py36h8c4c3a4_1`

**Comment by krafczyk** [comment]
Try
`conda env create -c conda-forge -f ./env.yaml -p ./venv`

**Comment by YifangZhang** [comment]
> (base) ITs-MacBook-Pro-2:python zhang303$ conda env create -c conda-forge -f ./env.yaml -p ./venv
> usage: conda-env [-h] {create,export,list,remove,update,config} ...
> conda-env: error: unrecognized arguments: -c
Seems like conda is not available for -c argument

My version is:

> (base) ITs-MacBook-Pro-2:python zhang303$ conda info
> 
>      active environment : base
>     active env location : /anaconda3
>             shell level : 1
>        user config file : /Users/zhang303/.condarc
>  populated config files : 
>           conda version : 4.8.3
>     conda-build version : 3.4.1
>          python version : 3.6.8.final.0
>        virtual packages : __osx=10.12.6
>        base environment : /anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/osx-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /anaconda3/pkgs
>                           /Users/zhang303/.conda/pkgs
>        envs directories : /anaconda3/envs
>                           /Users/zhang303/.conda/envs
>                platform : osx-64
>              user-agent : conda/4.8.3 requests/2.22.0 CPython/3.6.8 Darwin/16.7.0 OSX/10.12.6
>                 UID:GID : 502:20
>              netrc file : None
>            offline mode : False

**Comment by krafczyk** [comment]
Okay one more, try
`conda create -c conda-forge --file ./env.yaml -p ./venv`

**Comment by YifangZhang** [comment]
Says:
(base) ITs-MacBook-Pro-2:python zhang303$ conda create -c conda-forge --file ./env.yaml -p ./venv
CondaValueError: could not parse 'name: null' in: ./env.yaml

**Comment by krafczyk** [comment]
Try deleting the first line in the env.yaml file, it says 'name: null'

**Comment by krafczyk** [comment]
And then doing
`conda env create -f ./env.yaml -p ./venv`
again

**Comment by YifangZhang** [comment]
## first try ##
conda env create -f ./env.yaml -p ./venv
gives same results:
(base) ITs-MacBook-Pro-2:python zhang303$ conda env create -f ./env.yaml -p ./venv
Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound:

libdeflate==1.6=h516909a_0
xorg-libxdmcp==1.1.3=h516909a_0
...

## 2nd try ##
(base) ITs-MacBook-Pro-2:python zhang303$ conda create -c conda-forge --file ./env.yaml -p ./venv
CondaValueError: could not parse '- bioconda' in: ./env.yaml

**Comment by krafczyk** [comment]
Okay, delete the lines containing the libraries listed under `ResolvePackageNotFound`

And try again.

**Comment by krafczyk** [comment]
I think the env.yaml is dumping all kinds of libraries you can't use because you're on MAC. I'm trying to find a way to get an 'approximate' env.yaml and then give you that.

**Comment by YifangZhang** [comment]
That will be great, thanks a lot!

**Comment by krafczyk** [comment]
Okay, pull again, I've added a file `env-reduced.yaml` This should contain only those specs I requested when I built this environment. I'm expecting conda to solve all the dependencies necessary for mac.

Again, do `conda env create -f ./env-reduced.yaml -p ./venv`

**Comment by YifangZhang** [comment]
Now there are only 5 packages that are not solving:

> (base) ITs-MacBook-Pro-2:python zhang303$ conda env create -f ./env-reduced.yaml -p ./venv
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - pysam
>   - samtools
>   - phylogenetics
>   - phyml
>   - clustalw

**Comment by krafczyk** [comment]
Pull and try again,

The `bioconda` channel was missing for some reason.

Those are all bioconda libraries.

**Comment by YifangZhang** [comment]
YAY!!! It worked!!!

> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: \ b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'
> done
> #
> # To activate this environment, use
> #
> #     $ conda activate /Users/zhang303/Desktop/NCSA/c3ai_dti/jupyter/GenoExample/genomicsExample/python/venv
> #
> # To deactivate an active environment, use
> #
> #     $ conda deactivate
>
